### PR TITLE
rename AppProvider -> ThemeProvider

### PR DESCRIPTION
**Pull request by AndyLnd**

### CODE REVIEW

**Comment by ffflorian** [comment]
@AndyLnd Please squash and merge next time. Thanks!

**Comment by bennyn** [comment]
@ffflorian Have you set "squashing" to be the default?

image

**Comment by ffflorian** [comment]
@bennyn What do you mean by "default"? The options can only be enabled or disabled.

**Comment by bennyn** [comment]
So is it needed to keep "merge commits" and "rebase merging"?

**Comment by ffflorian** [comment]
Not sure. I can deactivate it for now and re-activate it if we need it later.

**Comment by bennyn** [comment]
Yeah, I think we will be good with just doing "squash merging". :)

**Pull request merged**
